### ISSUE TITLE
Stop Complaining When Hubot Gets Botsnacks

### ISSUE THREAD

**Issue by phily245** [JackRyder/SpotiiShuffle#3]
> <user1> hubot botsnack
> <Hubot> Om nom nom!
> <Spotifybot> Hubot is always stealing the snacks, greedy little robot.
> <user2> should prob tweak the regex to not say that if snack is directed at hubot

Pls can Spotifybot be less whiny?

**Comment by JackRyder** [comment]
> should prob tweak the regex

Implying it uses regex?

**Comment by JackRyder** [comment]
I've fixed this, will have to wait for it to be merged in. For now stop saying "hubot botsnack" ty.
